[[section]]
title = "Allgemeines"
title_en = "General"
[[section.link]]
desc = "Digicampus (Meine Veranstaltungen)"
desc_en = "Digicampus (My Courses)"
source = "/dc"
target = "https://digicampus.uni-augsburg.de/dispatch.php/my_courses"

[[section.link]]
desc = "Moodle"
source = "/moodle"
target = "https://moodle.uni-augsburg.de/"

[[section.link]]
desc = "STUDIS"
source = "/studis"
target = "https://studiswebstud.zv.uni-augsburg.de/FN2AUTH/FN2AuthServlet?op=Login&nologout=true"

[[section.link]]
desc = "VIBS"
source = "/vibs"
target = "https://vibs.uni-augsburg.de"

[[section.link]]
desc = "Webmail"
source = "/webmail"
target = "https://webmail.uni-augsburg.de/"

[[section.link]]
desc = "VPN"
source = "/vpn"
target = "https://confluence.rz.uni-augsburg.de/x/GIIo"

[[section.link]]
desc = "eduroam"
source = "/eduroam"
target = "https://confluence.rz.uni-augsburg.de/display/RZSER/Nutzung+von+eduroam#Nutzungvoneduroam-HiergehteszudenAnleitungenf%C3%BCrdieverschiedenenBetriebssysteme:"

[[section.link]]
desc = "Fachschaft Informatik"
desc_en = "Students' Association for Computer Science"
source = "/fs"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/studierendenvertretung/"

[[section.link]]
desc = "Fachschaft Mathematik"
desc_en = "Students' Association for Mathematics"
source = "/fsmath"
target = "https://www.uni-augsburg.de/de/fakultaet/mntf/math/fachschaft/"
target_en = "https://www.uni-augsburg.de/en/fakultaet/mntf/math/fachschaft/"

[[section.link]]
desc = "Studierendenrat"
source = "/stura"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/stura_fai/"

[[section.link]]
desc = "Klausurtermine"
desc_en = "Exam dates"
source = "/klausurtermine"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/im-studium/klausurtermine/"

[[section.link]]
desc = "Altklausuren"
desc_en = "Previous exams"
source = "/altklausuren"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/studierendenvertretung/altklausuren/"

[[section.link]]
desc = "Prüfungsamt"
desc_en = "Examination office"
source = "/pruefungsamt"
target = "https://www.uni-augsburg.de/de/studium/organisation-beratung/pruefungen/infos-und-antrage/fakultat-fur-angewandte-informatik-pruefungen/"

[[section.link]]
desc = "Mensa"
desc_en = "Canteen"
source = "/mensa"
target = "https://studierendenwerk-augsburg.de/essen-trinken/speiseplaene/"

[[section.link]]
desc = "Universitätsbibliothek"
desc_en = "Library"
source = "/bib"
target = "https://www.uni-augsburg.de/de/organisation/bibliothek/"

[[section.link]]
desc = "OPAC"
source = "/opac"
target = "https://opac.bibliothek.uni-augsburg.de/"

[[section.link]]
desc = "Hochschulsport"
desc_en = "University Sports"
source = "/sport"
target = "https://anmeldung.sport.uni-augsburg.de/angebote/aktueller_zeitraum/"

[[section.link]]
desc = "Mathe-Info Discord"
desc_en = "Discord for Math and Computer Science"
source = "/discord"
target = "https://discord.gg/SRYedBz"

[[section.link]]
desc = "Informationen zur Rückmeldung"
desc_en = "Information about Re-Registration"
source = "/rueckmeldung"
source_en = "/re-registration"
target = "https://www.uni-augsburg.de/de/studium/organisation-beratung/organisation-und-formales/rueckmeldung/"
target_en = "https://www.uni-augsburg.de/en/studium/organisation-beratung/organisation-und-formales/rueckmeldung/"

[[section.link]]
desc = "Stundenpläne, Lehrveranstaltungen und Module"
desc_en = "Schedules, lectures and modules"
source = "/lehrveranstaltungen"
source_en = "/courses"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/im-studium/lehre/"
target_en = "https://www.uni-augsburg.de/en/fakultaet/fai/informatik/im-studium/lehre/"

[[section.link]]
desc = "Fristen und Termine, Vorlesungszeiten, Vorlesungsfreie Tage"
desc_en = "Dates and Deadlines, holidays"
source = "/termine"
source_en = "/dates"
target = "https://www.uni-augsburg.de/de/studium/organisation-beratung/fristen-und-termine/"
target_en = "https://www.uni-augsburg.de/en/studium/organisation-beratung/fristen-und-termine/"

[[section.link]]
desc = "Beratungsangebote"
desc_en = "Student Advice and Counselling Service"
source = "/beratung"
source_en = "/counselling"
target = "https://www.uni-augsburg.de/de/studium/organisation-beratung/beratung/"
target_en = "https://www.uni-augsburg.de/en/studium/organisation-beratung/beratung/"


[[section]]
title = "1. Semester"
title_en = "1st Semester"
[[section.link]]
desc = "Informationen zum Studienstart"
desc_en = "Information about starting your studies"
source = "/studienstart"
source_en = "/start-of-studies"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/im-studium/studienstart/"
target_en = "https://www.uni-augsburg.de/en/fakultaet/fai/informatik/im-studium/studienstart/"

[[section.link]]
desc = "Informatik 1"
source = "/info1"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=a21c78d5d5c098c6835e90f667e7b7b9"

[[section.link]]
desc = "Programmierkurs"
source = "/prog"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=fe369e98f8717407cac69a6878291e99"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=3c0108874173b54b7d38a7278db393c6"

[[section.link]]
desc = "Mathematik für Informatiker I"
source = "/mfi1"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=aa6c0b4fe3ed05aaa8a3d5a1dd7f6f9b"

[[section.link]]
desc = "Diskrete Strukturen und Logik"
source = "/dislo"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=c44cae9e9618ecb9f795dfb7946dcf12"

[[section.link]]
desc = "Lineare Algebra I"
source = "/la1"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=d90e93ac8801f6e0f8d71d3c97adce8e"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=7a6962baafd363f26786ee5fd6b01813"


[[section]]
title = "2. Semester"
title_en = "2nd Semester"
[[section.link]]
desc = "Informatik 2"
source = "/info2"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=fbd22d77371804f13b3535cc2b441683"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=e48ce3c01e6fdc46665ef324116ee4fb"

[[section.link]]
desc = "Mathematik für Informatiker II"
source = "/mfi2"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=d69ae7bd9174d0217424387302b190e8"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=4edb5ac81536bc53949739f602db15a5"

[[section.link]]
desc = "Einführung in die Theoretische Informatik"
source = "/ti"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=681425c7c8957a32c34489ad386c8700"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=9c00aff4376e6e6cf7b93f315b7c56d0"

[[section.link]]
desc = "Analysis I"
source = "/ana1"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=28787c497f27ffdcf0b450fd0d2267ac"


[[section]]
title = "3. Semester"
title_en = "3rd Semester"
[[section.link]]
desc = "Informatik 3"
source = "/info3"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=a69ed97fa7cecf4a9a8e46dfa91873cb"

[[section.link]]
desc = "Stochastik für Informatiker"
source = "/sfi"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=eee02762342da92e8eb7cd9737f1594c"

[[section.link]]
desc = "Datenbanksysteme"
source = "/dbs"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=1d7a14ff64f099ca8baac1c9727a005c"


[[section]]
title = "4. Semester"
title_en = "4th Semester"
[[section.link]]
desc = "Systemnahe Informatik"
source = "/si"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=87178b102087f74d89a083e631a70938"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=dcface4ecfa9134ee078fe852591cb49"

[[section.link]]
desc = "Softwareprojekt"
source = "/sopro"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=642fe1eeaff1e4369dd544f37d3f7ef9"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=17d0d4d40882454657836b4999bb1dd7"

[[section.link]]
desc = "Grundlagen der Human-Computer-Interaction / Multimedia Grundlagen II"
source = "/ghci"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=65514e5f51a949d7bda694c9a841e2a9"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=22de509345a969f74ea16ce65a448476"


[[section]]
title = "5. Semester"
title_en = "5th Semester"
[[section.link]]
desc = "Kommunikationssysteme"
source = "/kommsys"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=66072c407605c92b4f3bc0678bc25ee6"

[[section.link]]
desc = "Softwaretechnik"
source = "/swt"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=42e90b965f0c78242e5426cd1bda8b86"

[[section.link]]
desc = "Grundlagen der Signalverarbeitung und des maschinellen Lernens / Multimedia Grundlagen I"
source = "/svml"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=f4aced9eaedf96f253c242ed18803768"


[[section]]
title = "Modulhandbuch"
title_en = "Handbook of modules"
[[section.link]]
desc = "Informatik"
desc_en = "Computer Science"
source = "/mhb-inf"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/3849680e7037bbbd26bf2e1a62dca925"

[[section.link]]
desc = "Informatik und Multimedia"
desc_en = "Medical Information Sciences"
source = "/mhb-infmm"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/3c34b406fd7ecc203a2377e5110d740b"

[[section.link]]
desc = "Medizinische Informatik"
desc_en = "Medical Information Sciences"
source = "/mhb-medinf"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/2c775b6c20922d412963956168546227"

[[section.link]]
desc = "Ingenieurinformatik"
desc_en = "Computer Science in Engineering"
source = "/mhb-inginf"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/53b4c5ab2256b9cc65d073375f195577"

[[section.link]]
desc = "Geoinformatik"
desc_en = "Geoinformatics"
source = "/mhb-geoinf"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/160191277da9ccf0d59c6f12015b7d22"

[[section.link]]
desc = "Wirtschaftsinformatik"
desc_en = "Business & Information Systems Engineering"
source = "/mhb-win"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/d83e48e4bf153c904ea3b6567051fc33"

[[section.link]]
desc = "Data Science"
source = "/mhb-ds"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/7f0cf0b456169d91be776186d9601388"

[[section.link]]
desc = "Mathematik und Informatik"
desc_en = "Mathematics and Computer Science"
source = "/mhb-mui"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/466e9c52a2eb140e4bd623c454865d03"


[[section]]
title = "Prüfungsordnung"
title_en = "Examination regulations"
[[section.link]]
desc = "Informatik"
desc_en = "Computer Science"
source = "/po-inf"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-informatik/"

[[section.link]]
desc = "Informatik und Multimedia"
source = "/po-infmm"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-informatik-und-multimedia/"

[[section.link]]
desc = "Medizinische Informatik"
desc_en = "Medical Information Sciences"
source = "/po-medinf"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-medizinische-informatik/"

[[section.link]]
desc = "Ingenieurinformatik"
desc_en = "Computer Science in Engineering"
source = "/po-inginf"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-ingenieurinformatik/"

[[section.link]]
desc = "Geoinformatik"
desc_en = "Geoinformatics"
source = "/po-geoinf"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-geoinformatik/"

[[section.link]]
desc = "Wirtschaftsinformatik"
desc_en = "Business & Information Systems Engineering"
source = "/po-win"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-wirtschaftsinformatik/"

[[section.link]]
desc = "Data Science"
source = "/po-ds"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/BScDataSc/"

[[section.link]]
desc = "Mathematik und Informatik"
desc_en = "Mathematics and Computer Science"
source = "/po-mui"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/BSCMathInf/"


[[section]]
title = "Fachschaft Informatik (asinf)"
title_en = "Students' Association for Computer Science (asinf)"
[[section.link]]
desc = "Awareness"
source = "/awareness"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/studierendenvertretung/awareness/"

[[section.link]]
desc = "Erstiheft Informatik"
source = "/erstiheft"
target = "https://fachschaft-info.de/erstiheft.pdf"

[[section.link]]
desc = "Anmeldung Kneipentour"
source = "/kneipentour"
target = "https://forms.gle/nYCorjSTnEbD33d6A"

[[section.link]]
desc = "Anmeldung Scotland Yard"
source = "/scotlandyard"
target = "https://docs.google.com/forms/d/e/1FAIpQLSfmuAQ8t-KxngSo_jgdUAE6hZI7PhutgcKN6F7poBeSuReFQg/viewform"

[[section.link]]
desc = "Uni Augsburg Meisterschaft in Mario Kart 8 Deluxe"
source = "/mariokart"
target = "https://fachschaft-info.de/mariokart/"


