[[section]]
title = "Allgemeines"
[[section.link]]
desc = "Digicampus (Meine Veranstaltungen)"
source = "/dc"
target = "https://digicampus.uni-augsburg.de/dispatch.php/my_courses"

[[section.link]]
desc = "Moodle"
source = "/moodle"
target = "https://moodle.uni-augsburg.de/"

[[section.link]]
desc = "STUDIS"
source = "/studis"
target = "https://studiswebstud.zv.uni-augsburg.de/FN2AUTH/FN2AuthServlet?op=Login&nologout=true"

[[section.link]]
desc = "VIBS"
source = "/vibs"
target = "https://vibs.uni-augsburg.de"

[[section.link]]
desc = "Webmail"
source = "/webmail"
target = "https://webmail.uni-augsburg.de/"

[[section.link]]
desc = "VPN"
source = "/vpn"
target = "https://confluence.rz.uni-augsburg.de/x/GIIo"

[[section.link]]
desc = "eduroam"
source = "/eduroam"
target = "https://confluence.rz.uni-augsburg.de/display/RZSER/Nutzung+von+eduroam#Nutzungvoneduroam-HiergehteszudenAnleitungenf%C3%BCrdieverschiedenenBetriebssysteme:"

[[section.link]]
desc = "Fachschaft Informatik"
source = "/fs"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/studierendenvertretung/"

[[section.link]]
desc = "Fachschaft Mathematik"
source = "/fsmath"
target = "https://www.uni-augsburg.de/de/fakultaet/mntf/math/fachschaft/"

[[section.link]]
desc = "Klausurtermine"
source = "/klausurtermine"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/im-studium/klausurtermine/"

[[section.link]]
desc = "Altklausuren"
source = "/altklausuren"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/studierendenvertretung/altklausuren/"

[[section.link]]
desc = "Prüfungsamt"
source = "/pruefungsamt"
target = "https://www.uni-augsburg.de/de/studium/organisation-beratung/pruefungen/infos-und-antrage/fakultat-fur-angewandte-informatik-pruefungen/"

[[section.link]]
desc = "Mensa"
source = "/mensa"
target = "https://studentenwerk.online/hg-oeffnungszeiten"

[[section.link]]
desc = "Universitätsbibliothek"
source = "/bib"
target = "https://www.uni-augsburg.de/de/organisation/bibliothek/"

[[section.link]]
desc = "OPAC"
source = "/opac"
target = "https://opac.bibliothek.uni-augsburg.de/"

[[section.link]]
desc = "Hochschulsport"
source = "/sport"
target = "https://anmeldung.sport.uni-augsburg.de/angebote/aktueller_zeitraum/"

[[section.link]]
desc = "Mathe-Info Discord"
source = "/discord"
target = "https://discord.gg/SRYedBz"

[[section.link]]
desc = "MakeHub Kalender"
source = "/makehub-kal"
target = "https://makehub-cal.uni-augsburg.de/Web"

[[section.link]]
desc = "Informationen zur Rückmeldung"
source = "/rueckmeldung"
target = "https://www.uni-augsburg.de/de/studium/organisation-beratung/organisation-und-formales/rueckmeldung/"

[[section.link]]
desc = "Stundenpläne, Lehrveranstaltungen und Module"
source = "/lehrveranstaltungen"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/im-studium/lehre/"

[[section.link]]
desc = "Fristen und Termine, Vorlesungszeiten, Vorlesungsfreie Tage"
source = "/termine"
target = "https://www.uni-augsburg.de/de/studium/organisation-beratung/fristen-und-termine/"

[[section.link]]
desc = "Beratungsangebote"
source = "/beratung"
target = "https://www.uni-augsburg.de/de/studium/organisation-beratung/beratung/"


[[section]]
title = "1. Semester"
[[section.link]]
desc = "Informationen für Erstsemester"
source = "/ersti"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/im-studium/studienanfanger/"

[[section.link]]
desc = "Informationen zu Vor-/Brückenkursen"
source = "/vorkurs"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/im-studium/vorkurs/"

[[section.link]]
desc = "Informatik 1"
source = "/info1"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=50d710d5a0fcdfcedd1adf7d5f24af44"

[[section.link]]
desc = "Programmierkurs"
source = "/prog"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=fe369e98f8717407cac69a6878291e99"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=3c0108874173b54b7d38a7278db393c6"

[[section.link]]
desc = "Mathematik für Informatiker I"
source = "/mfi1"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=776edc9c59569c077e5badbaea96c691"

[[section.link]]
desc = "Diskrete Strukturen und Logik"
source = "/dislo"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=aa2f05511e2df7f2aebf6014238b8614"

[[section.link]]
desc = "Lineare Algebra I"
source = "/la1"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=d90e93ac8801f6e0f8d71d3c97adce8e"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=7a6962baafd363f26786ee5fd6b01813"


[[section]]
title = "2. Semester"
[[section.link]]
desc = "Informatik 2"
source = "/info2"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=fbd22d77371804f13b3535cc2b441683"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=e48ce3c01e6fdc46665ef324116ee4fb"

[[section.link]]
desc = "Mathematik für Informatiker II"
source = "/mfi2"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=d69ae7bd9174d0217424387302b190e8"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=4edb5ac81536bc53949739f602db15a5"

[[section.link]]
desc = "Einführung in die Theoretische Informatik"
source = "/ti"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=681425c7c8957a32c34489ad386c8700"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=9c00aff4376e6e6cf7b93f315b7c56d0"

[[section.link]]
desc = "Analysis I"
source = "/ana1"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=54bb6adf47e2097662d9e0eeead6277a"


[[section]]
title = "3. Semester"
[[section.link]]
desc = "Informatik 3"
source = "/info3"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=148c0bb713797e5a56e6f71155f9e88c"

[[section.link]]
desc = "Stochastik für Informatiker"
source = "/sfi"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=d155c4e909132be5b8c4a00303fd48eb"

[[section.link]]
desc = "Datenbanksysteme"
source = "/dbs"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=f3c545a7b62f31118150daf6b69df33c"


[[section]]
title = "4. Semester"
[[section.link]]
desc = "Systemnahe Informatik"
source = "/si"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=87178b102087f74d89a083e631a70938"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=dcface4ecfa9134ee078fe852591cb49"

[[section.link]]
desc = "Softwareprojekt"
source = "/sopro"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=642fe1eeaff1e4369dd544f37d3f7ef9"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=17d0d4d40882454657836b4999bb1dd7"

[[section.link]]
desc = "Grundlagen der Human-Computer-Interaction / Multimedia Grundlagen II"
source = "/ghci"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=65514e5f51a949d7bda694c9a841e2a9"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=22de509345a969f74ea16ce65a448476"


[[section]]
title = "5. Semester"
[[section.link]]
desc = "Kommunikationssysteme"
source = "/kommsys"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=e4e5323f640fd6c9a962fe4885cfc424"

[[section.link]]
desc = "Softwaretechnik"
source = "/swt"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=60acd8cdf7b5248b1e06d3364b1c9503"

[[section.link]]
desc = "Grundlagen der Signalverarbeitung und des maschinellen Lernens / Multimedia Grundlagen I"
source = "/svml"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=52f9d1add772abe35cc31274d73d5c1a"


[[section]]
title = "Wahlbereich"

[[section]]
title = "Modulhandbuch"
[[section.link]]
desc = "Informatik"
source = "/mhb-inf"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/3849680e7037bbbd26bf2e1a62dca925"

[[section.link]]
desc = "Informatik und Multimedia"
source = "/mhb-infmm"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/3c34b406fd7ecc203a2377e5110d740b"

[[section.link]]
desc = "Medizinische Informatik"
source = "/mhb-medinf"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/2c775b6c20922d412963956168546227"

[[section.link]]
desc = "Ingenieurinformatik"
source = "/mhb-inginf"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/53b4c5ab2256b9cc65d073375f195577"

[[section.link]]
desc = "Geoinformatik"
source = "/mhb-geoinf"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/160191277da9ccf0d59c6f12015b7d22"

[[section.link]]
desc = "Wirtschaftsinformatik"
source = "/mhb-win"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/d83e48e4bf153c904ea3b6567051fc33"

[[section.link]]
desc = "Data Science"
source = "/mhb-ds"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/7f0cf0b456169d91be776186d9601388"

[[section.link]]
desc = "Mathematik und Informatik"
source = "/mhb-mui"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/466e9c52a2eb140e4bd623c454865d03"


[[section]]
title = "Prüfungsordnung"
[[section.link]]
desc = "Informatik"
source = "/po-inf"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-informatik/"

[[section.link]]
desc = "Informatik und Multimedia"
source = "/po-infmm"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-informatik-und-multimedia/"

[[section.link]]
desc = "Medizinische Informatik"
source = "/po-medinf"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-medizinische-informatik/"

[[section.link]]
desc = "Ingenieurinformatik"
source = "/po-inginf"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-ingenieurinformatik/"

[[section.link]]
desc = "Geoinformatik"
source = "/po-geoinf"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-geoinformatik/"

[[section.link]]
desc = "Wirtschaftsinformatik"
source = "/po-win"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-wirtschaftsinformatik/"

[[section.link]]
desc = "Data Science"
source = "/po-ds"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/BScDataSc/"

[[section.link]]
desc = "Mathematik und Informatik"
source = "/po-mui"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/BSCMathInf/"


[[section]]
title = "Fachschaft Informatik (asinf)"
[[section.link]]
desc = "Erstiheft Informatik"
source = "/erstiheft"
target = "https://fachschaft-info.de/erstiheft.pdf"

[[section.link]]
desc = "Anmeldung Kneipentour"
source = "/kneipentour"
target = "https://forms.gle/PJtKapRgZiLdYVYe8"

[[section.link]]
desc = "Anmeldung Pubquiz"
source = "/pubquiz"
target = "https://docs.google.com/forms/d/e/1FAIpQLSe8640ciO2pfSzE6M2YUtwBXXSwUNvamvFvYpNisMTHQ_R0OQ/viewform?usp=sf_link"
